# Generated by Django 4.2.1 on 2023-06-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0002_rename_cargo_especialidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesional',
            old_name='Especialidad',
            new_name='especialidad',
        ),
        migrations.AddField(
            model_name='profesional',
            name='foto',
            field=models.ImageField(null=True, upload_to='profesional'),
        ),
    ]
