# Generated by Django 4.2.1 on 2023-06-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0008_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.IntegerField(choices=[[0, 'Pendiente'], [1, 'Aceptado'], [2, 'Rechazado']]),
        ),
    ]
