# Generated by Django 4.2.1 on 2023-06-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0009_alter_solicitud_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
