# Generated by Django 4.2.1 on 2023-06-29 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0010_delete_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.IntegerField(choices=[[0, 'Cambio de neumáticos'], [1, 'Cambio de aceite'], [2, 'Abolladura'], [3, 'Revisión de batería'], [4, 'Cambio de batería'], [5, 'Revisión de niveles'], [6, 'Caja de cambio'], [7, 'Cambio de pastillas de freno'], [8, 'Limpieza']])),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('fecha', models.DateField(null=True)),
                ('foto', models.ImageField(null=True, upload_to='profesional')),
                ('estado', models.IntegerField(choices=[[0, 'Pendiente'], [1, 'Aceptado'], [2, 'Rechazado']])),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.profesional')),
            ],
        ),
    ]
