# Generated by Django 4.2.1 on 2023-06-29 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0011_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.IntegerField(choices=[[0, 'Pendiente'], [1, 'Aceptado'], [2, 'Rechazado'], [3, 'Completado']], null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto',
            field=models.ImageField(null=True, upload_to='solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='profesional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appweb.profesional'),
        ),
    ]
