# Generated by Django 4.2.1 on 2023-07-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0012_alter_solicitud_estado_alter_solicitud_foto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('telefono', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('experiencia', models.TextField()),
                ('foto', models.ImageField(null=True, upload_to='postular')),
            ],
        ),
    ]
