# Generated by Django 4.2.1 on 2023-07-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0014_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profesional'),
        ),
    ]
