# Generated by Django 4.2.1 on 2023-07-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0016_postular_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
